apiVersion: batch/v1
kind: Job
metadata:
  name: nautible-app-ms-stock-batch-quantity-check
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: nautible-app-ms-stock-batch
    app.kubernetes.io/instance: nautible-app-ms-stock-batch
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  parallelism: 1
  completions: 1
  manualSelector: true
  selector:
    matchLabels:
      app.kubernetes.io/instance: nautible-app-ms-stock-batch
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nautible-app-ms-stock-batch
        app.kubernetes.io/instance: nautible-app-ms-stock-batch
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: nautible
        app.kubernetes.io/managed-by: manual
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nautible-app-ms-stock-batch-quantity-check"
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }' # https://github.com/dapr/dapr/issues/2657
    spec:
      containers:
      - name: nautible-app-ms-stock-batch-quantity-check
        image: public.ecr.aws/nautible/nautible-app-ms-stock-batch:dummy
        env:
        - name: QUARKUS_PROFILE
          value: aws-local-dev
        - name: QUARKUS_PICOCLI_TOP_COMMAND
          value: quantity-check
      restartPolicy: Never
