apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nautible-app-ms-stock-batch-quantity-check
  namespace: nautible-app-ms
spec:
  templates:
    - name: nautible-app-ms-stock-batch-quantity-check
      container:
        image: public.ecr.aws/nautible/nautible-app-ms-stock-batch:3b7615f01888d0c7b13ddebcd707433862fe802d
        env:
          - name: QUARKUS_PROFILE
            value: "aws-dev"
          - name: QUARKUS_PICOCLI_TOP_COMMAND
            value: "quantity-check"
