apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nautible-app-ms-stock-batch-quantity-check
  namespace: nautible-app-ms
spec:
  templates:
    - name: nautible-app-ms-stock-batch-quantity-check
      container:
        image: public.ecr.aws/nautible/nautible-app-ms-stock-batch:e806668f593e31057ec7a3514a9b97759daa7524
        env:
          - name: QUARKUS_PROFILE
            value: "aws-dev"
          - name: QUARKUS_PICOCLI_TOP_COMMAND
            value: "quantity-check"
