apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nautible-app-ms-stock-batch-quantity-check
  namespace: nautible-app-ms
spec:
  templates:
    - name: nautible-app-ms-stock-batch-quantity-check
      container:
        image: nautibledevacr.azurecr.io/nautible-app-ms-stock-batch:d8c864e9ae54c0ee1abc904d8da05f2f6954a3b9
        env:
          - name: QUARKUS_PROFILE
            value: "azure-dev"
          - name: QUARKUS_PICOCLI_TOP_COMMAND
            value: "quantity-check"
