apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nautible-app-ms-stock-batch-quantity-check
  namespace: nautible-app-ms
spec:
  templates:
    - name: nautible-app-ms-stock-batch-quantity-check
      container:
        image: nautibledevacr.azurecr.io/nautible-app-ms-stock-batch:4e12c168fc5d9e71a7ba2223c7e099e7c0b986c9
        env:
          - name: QUARKUS_PROFILE
            value: "azure-dev"
          - name: QUARKUS_PICOCLI_TOP_COMMAND
            value: "quantity-check"
